var Case = [
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画一",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画二",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画三",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画四",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画五",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画六",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画七",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画八",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画九",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画十",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画十一",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画十二",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画十三",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"美美动画十四",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
]

var Item = [
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画一",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画二",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画三",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画四",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画五",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画六",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画七",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画八",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画九",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画十",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画十一",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画十二",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画十三",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"项目动画十四",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
]


var Team = [
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画一",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画二",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画三",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画四",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画五",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画六",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画七",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画八",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画九",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画十",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画十一",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画十二",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画十三",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
	{
		ContImg:'images/CaseListImg1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/CaseListImg1.jpg*/,
		title:"团队动画十四",
		Icon1:'images/Icon1.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon1.jpg*/,
		Icon2:'images/Icon2.jpg'/*tpa=http://www.miaov.com/student/xiangling/json/images/Icon2.jpg*/,
		Txt:'美美动漫以手机原创动漫为方向，借助最新的最好技术手段，',
		More:'More>>'
	},
]

